name: Check Renderability

on:
  pull_request:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2

      - name: Verify nonexistence of `rendered`
        shell: bash
        run: if [ -e rendered ]; then exit 1; fi

      - name: Set git config
        run: git config --global --add safe.directory /github/workspace

      - name: Set base ref
        run: git show-ref --heads --hash -- "${{ github.base_ref }}" |tee base_ref

      - name: Compile ZIPs and Zcash Protocol Specification
        uses: ./.github/actions/render
